# Files for typos
# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started

[default.extend-identifiers]

[default.extend-words]

ono = "ono"

[files]
extend-exclude = ['package*.json', 'node_modules', 'pnpm-lock.yaml']
