[tool.poetry]
name = "koniwa"
version = "0.1.0"
description = ""
authors = ["Yuta Hayashibe <yuta@hayashibe.jp>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
coverage = ">=5.3"
flake8 = ">=3.8.4"
isort = ">=5.6.4"
yamllint = ">=1.25.0"
pydocstyle = ">=5.1.1"
pyright = ">=0.0.10"
# 21.8b0 and 21.9b0 cause ImportError: cannot import name 'TypeGuard' from 'typing_extensions'
black = "<21.8b0"
toml = "^0.10.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
pythonVersion = "3.7"
typeCheckingMode = "basic"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
