---
version: '3'

vars:
  OUTPUT_STAT: /dev/stdout

tasks:
  default:
    deps: [format, lint, test]

  check_json:
    cmds:
      - python3 -m koniwa.check_json -i ./data -o {{ .OUTPUT_STAT }}

  lint_and_test:
    deps: [lint, test]

  format:
    cmds:
      - ruff format --respect-gitignore
      - ruff check --fix
      - pnpm format

  lint:
    deps: [lint_yaml, lint_ruff_format, lint_ruff_check, lint_pnpm]

  lint_yaml:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
         -prune -o -type f \( -name "*.yaml" -o -name "*.yml" \) -print \
        | xargs yamllint

  lint_ruff_format:
    cmds:
      - ruff format --respect-gitignore --check

  lint_ruff_check:
    cmds:
      - ruff check --respect-gitignore

  lint_pnpm:
    cmds:
      - pnpm lint

  lint_typos:
    cmds:
      - typos -V && typos

  test:
    cmds:
      - pnpm test
