---
version: '3'

vars:
  OUTPUT_STAT: /dev/stdout

tasks:
  default:
    deps: [format, lint, test]

  check_json:
    cmds:
      - python3 -m koniwa.check_json -i ./data -o {{ .OUTPUT_STAT }}

  format:
    cmds:
      - ruff format --respect-gitignore
      - ruff check --fix
      - pnpm format

  lint:
    deps: [lint_yaml]
    cmds:
      - ruff format --respect-gitignore --check
      - ruff check --respect-gitignore
      - pnpm lint

  lint_yaml:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
          -prune -o -type f -name '*.yml' -print \
        | xargs yamllint --no-warnings -c .yamllint.yml

  lint_shell:
    cmds:
      - >-
        find . \( -name node_modules -o -name .venv \) \
          -prune -o -type f -name '*.yml' -print \
        | xargs shellcheck

  lint_typos:
    cmds:
      - typos -V && typos

  test:
    cmds:
      - pnpm test
